import { createContext, useContext, useEffect, useState, ReactNode } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";

export type Language = "English" | "Hindi" | "French" | "Spanish" | "German" | "Japanese" | "Chinese";

export const SUPPORTED_LANGUAGES: { name: Language; label: string; emoji: string }[] = [
  { name: "English", label: "English", emoji: "🇺🇸" },
  { name: "Hindi", label: "हिंदी", emoji: "🇮🇳" },
  { name: "French", label: "Français", emoji: "🇫🇷" },
  { name: "Spanish", label: "Español", emoji: "🇪🇸" },
  { name: "German", label: "Deutsch", emoji: "🇩🇪" },
  { name: "Japanese", label: "日本語", emoji: "🇯🇵" },
  { name: "Chinese", label: "中文", emoji: "🇨🇳" }
];

type Translations = Record<string, string>;

const TRANSLATIONS: Record<Language, Translations> = {
  English: {
    dashboard: "Dashboard",
    explore: "Explore",
    generateLesson: "Generate Lesson",
    myLibrary: "My Library",
    profile: "Profile",
    logout: "Logout",
    welcomeBack: "Welcome back",
    totalLessons: "Total lessons",
    teacherAccount: "Teacher Account",
    studentAccount: "Student Account",
    last7Days: "Last 7 days",
    recentLessons: "Recent lessons",
    availableMaterials: "Available study materials",
    createFirstLesson: "Create your first lesson",
    noLessonsYet: "No lessons yet.",
    noLessonsPublished: "No lessons published by teachers yet.",
    saveProfile: "Save profile",
    teacherDetails: "Teacher details",
    school: "School",
    subjectSpecialty: "Subject specialty",
    webhookUrl: "Webhook URL",
    saveWebhook: "Save webhook",
    geminiApiIntegration: "Gemini AI Integration",
    geminiApiKey: "Gemini API Key",
    saveApiKey: "Save API Key",
    lessonKit: "Lesson kit",
    lessonPlan: "Lesson Plan",
    worksheet: "Worksheet",
    quiz: "Practice Quiz",
    answerKey: "Answer Key",
    regenerate: "Regenerate",
    save: "Save",
    publish: "Publish",
    published: "Published",
    email: "Email",
    backToLibrary: "Back to library",
    backHome: "Back home",
    studyMaterialLibrary: "Study material library",
    searchPlaceholder: "Search by title, subject, or topic...",
    lessonDetails: "Lesson details",
    subject: "Subject",
    grade: "Grade",
    topic: "Topic",
    duration: "Duration",
    language: "Language",
    learningObjectives: "Learning objectives",
    generate: "Generate Lesson",
    generating: "Generating...",
    assistantTitle: "AI Study Assistant",
    assistantWelcome: "Hi! I'm your TechFlow AI Study Assistant. Ask me anything related to learning, teaching, revision, lesson planning or educational content.",
    chatPlaceholder: "Ask a question...",
    quickSummary: "Summarize key points",
    quickQuiz: "Ask me a question",
    quickSimplify: "Explain simply",
    send: "Send",
    newLesson: "New lesson",
    welcomeText: "Your AI teaching assistant.",
    welcomeStudentText: "Explore lessons published by teachers.",
    studyMaterial: "Study material",
    apiPlaceholder: "AIzaSy...",
    emailCopied: "Lesson copied to clipboard",
    connectedWebhook: "Connected: Make.com Webhook",
    connectedGemini: "Connected: Gemini AI (Direct)",
    builtInDemo: "Using built-in demo generator. Add a Gemini API key or Webhook in your Profile for real AI.",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    flashcards: "Flashcards",
    quizGenerator: "Quiz Generator",
    flip: "Flip",
    next: "Next",
    previous: "Previous",
    shuffle: "Shuffle",
    download: "Download",
    difficulty: "Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    readAloud: "Read Aloud",
    pause: "Pause",
    resume: "Resume",
    stop: "Stop",
    regenerateFlashcards: "Regenerate Cards",
    cardIndex: "Card {current} of {total}",
    downloadPdf: "Download PDF",
    downloadFullKit: "Download Full Kit PDF",
    rubric: "Grading Rubric",
    homework: "Homework",
    generateRubric: "Generate Rubric",
    generateHomework: "Generate Homework",
    versions: "Version History",
    duplicate: "Duplicate Lesson",
    restore: "Restore",
    restored: "Version restored successfully",
    viewPreviousVersions: "Version History",
    selectVersion: "Select a version to restore",
    duplicationDialogTitle: "Duplicate & Customize Lesson",
    assessmentType: "Assessment Type",
    estimatedTime: "Estimated Time",
    difficultyLevel: "Difficulty Level",
    revertToThis: "Restore this version",
    lessonsCreated: "Lessons Created",
    lessonsPublished: "Lessons Published",
    lessonsShared: "Lessons Shared",
    studentViews: "Student Views",
    subjectDistribution: "Subject Distribution",
    gradeDistribution: "Grade Distribution",
    usageTrends: "Lesson Usage Trends",
    noVersions: "No older versions found for this lesson.",
    analytics: "Analytics",
    myProgress: "My Progress",
    classProgress: "Class Progress",
    assignments: "Assignments",
    createAssignment: "Create Assignment",
    assignmentUrl: "Assignment Link",
    dueDate: "Due Date",
    submitAssignment: "Submit Assignment",
    submissions: "Submissions",
    streak: "Streak",
    points: "Points",
    achievements: "Achievements",
    leaderboard: "Leaderboard",
    aiRecommendations: "AI Recommendations",
    generateRecommendations: "Generate Recommendations",
    studyPlan: "Study Plan",
    generateStudyPlan: "Generate Study Plan",
    feedback: "Feedback",
    score: "Score",
    gradeAssignment: "Grade Assignment",
    aiTutor: "AI Tutor",
    studyGuides: "Study Guides & Summaries",
    shortSummary: "Short Summary",
    revisionNotes: "Revision Notes",
    examNotes: "Exam Notes",
    oneMinuteReview: "1-Min Review",
    askAiTutor: "Ask AI Tutor"
  },
  Hindi: {
    dashboard: "डैशबोर्ड",
    explore: "खोजें",
    generateLesson: "पाठ तैयार करें",
    myLibrary: "मेरी लाइब्रेरी",
    profile: "प्रोफ़ाइल",
    logout: "लॉगआउट",
    welcomeBack: "आपका स्वागत है",
    totalLessons: "कुल पाठ",
    teacherAccount: "शिक्षक खाता",
    studentAccount: "छात्र खाता",
    last7Days: "पिछले ७ दिन",
    recentLessons: "हाल के पाठ",
    availableMaterials: "उपलब्ध अध्ययन सामग्री",
    createFirstLesson: "अपना पहला पाठ बनाएं",
    noLessonsYet: "अभी तक कोई पाठ नहीं है।",
    noLessonsPublished: "शिक्षकों द्वारा अभी तक कोई पाठ प्रकाशित नहीं किया गया है।",
    saveProfile: "प्रोफ़ाइल सहेजें",
    teacherDetails: "शिक्षक विवरण",
    school: "विद्यालय",
    subjectSpecialty: "विषय विशेषता",
    webhookUrl: "वेबहुक URL",
    saveWebhook: "वेबहुक सहेजें",
    geminiApiIntegration: "जेमिनी एआई एकीकरण",
    geminiApiKey: "जेमिनी एआई कुंजी",
    saveApiKey: "एआई कुंजी सहेजें",
    lessonKit: "पाठ किट",
    lessonPlan: "पाठ योजना",
    worksheet: "कार्यपत्रक (Worksheet)",
    quiz: "अभ्यास प्रश्नोत्तरी",
    answerKey: "उत्तर कुंजी",
    regenerate: "पुनः उत्पन्न करें",
    save: "सहेजें",
    publish: "प्रकाशित करें",
    published: "प्रकाशित",
    email: "ईमेल",
    backToLibrary: "लाइब्रेरी पर वापस जाएं",
    backHome: "मुख्य पृष्ठ",
    studyMaterialLibrary: "अध्ययन सामग्री लाइब्रेरी",
    searchPlaceholder: "शीर्षक, विषय या विषय-वस्तु से खोजें...",
    lessonDetails: "पाठ का विवरण",
    subject: "विषय",
    grade: "कक्षा",
    topic: "विषय-वस्तु",
    duration: "अवधि",
    language: "भाषा",
    learningObjectives: "सीखने के उद्देश्य",
    generate: "पाठ उत्पन्न करें",
    generating: "उत्पन्न हो रहा है...",
    assistantTitle: "एआई अध्ययन सहायक",
    assistantWelcome: "नमस्ते! मैं आपका टेकफ्लो एआई अध्ययन सहायक हूं। मुझसे सीखने, पढ़ाने, दोहराने, पाठ योजना बनाने या शैक्षिक सामग्री से संबंधित कुछ भी पूछें।",
    chatPlaceholder: "एक प्रश्न पूछें...",
    quickSummary: "मुख्य बिंदुओं का सारांश",
    quickQuiz: "मुझसे एक प्रश्न पूछें",
    quickSimplify: "सरल भाषा में समझाएं",
    send: "भेजें",
    newLesson: "नया पाठ",
    welcomeText: "आपका एआई शिक्षण सहायक।",
    welcomeStudentText: "शिक्षकों द्वारा प्रकाशित पाठों का अन्वेषण करें।",
    studyMaterial: "अध्ययन सामग्री",
    apiPlaceholder: "AIzaSy...",
    emailCopied: "पाठ क्लिपबोर्ड पर कॉपी किया गया",
    connectedWebhook: "कनेक्टेड: Make.com वेबहुक",
    connectedGemini: "कनेक्टेड: जेमिनी एआई (सीधा)",
    builtInDemo: "अंतर्निहित डेमो जनरेटर का उपयोग कर रहे हैं। वास्तविक एआई के लिए अपनी प्रोफ़ाइल में जेमिनी एआई कुंजी या वेबहुक जोड़ें।",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    flashcards: "फ़्लैशकार्ड",
    quizGenerator: "प्रश्नोत्तरी जनरेटर",
    flip: "पलटें",
    next: "अगला",
    previous: "पिछला",
    shuffle: "सफ़ल करें",
    download: "डाउनलोड करें",
    difficulty: "कठिनाई",
    easy: "आसान",
    medium: "मध्यम",
    hard: "कठिन",
    readAloud: "सस्वर पाठ",
    pause: "विराम",
    resume: "फिर शुरू करें",
    stop: "रोकें",
    regenerateFlashcards: "कार्ड पुनः उत्पन्न करें",
    cardIndex: "{total} का कार्ड {current}",
    downloadPdf: "पीडीएफ डाउनलोड करें",
    downloadFullKit: "पूर्ण किट पीडीएफ डाउनलोड करें",
    rubric: "ग्रेडिंग रूब्रिक",
    homework: "गृहकार्य",
    generateRubric: "रूब्रिक तैयार करें",
    generateHomework: "गृहकार्य तैयार करें",
    versions: "संस्करण इतिहास",
    duplicate: "पाठ की प्रतिलिपि बनाएँ",
    restore: "पुनर्स्थापित करें",
    restored: "संस्करण सफलतापूर्वक पुनर्स्थापित किया गया",
    viewPreviousVersions: "संस्करण इतिहास",
    selectVersion: "पुनर्स्थापित करने के लिए संस्करण चुनें",
    duplicationDialogTitle: "पाठ की प्रतिलिपि बनाएँ और अनुकूलित करें",
    assessmentType: "मूल्यांकन प्रकार",
    estimatedTime: "अनुमानित समय",
    difficultyLevel: "कठिनाई स्तर",
    revertToThis: "इस संस्करण को पुनर्स्थापित करें",
    lessonsCreated: "तैयार किए गए पाठ",
    lessonsPublished: "प्रकाशित पाठ",
    lessonsShared: "साझा किए गए पाठ",
    studentViews: "छात्र विचार",
    subjectDistribution: "विषय वितरण",
    gradeDistribution: "कक्षा वितरण",
    usageTrends: "पाठ उपयोग रुझान",
    noVersions: "इस पाठ के लिए कोई पुराना संस्करण नहीं मिला।",
    analytics: "विश्लेषण",
    myProgress: "मेरी प्रगति",
    classProgress: "कक्षा की प्रगति",
    assignments: "सत्र कार्य (Assignments)",
    createAssignment: "सत्र कार्य बनाएं",
    assignmentUrl: "सत्र कार्य लिंक",
    dueDate: "नियत तारीख",
    submitAssignment: "सत्र कार्य जमा करें",
    submissions: "जमा किए गए कार्य",
    streak: "लगातार दिन (Streak)",
    points: "अंक (Points)",
    achievements: "उपलब्धियां",
    leaderboard: "लीडरबोर्ड",
    aiRecommendations: "एआई सिफारिशें",
    generateRecommendations: "सिफारिशें उत्पन्न करें",
    studyPlan: "अध्ययन योजना",
    generateStudyPlan: "अध्ययन योजना बनाएं",
    feedback: "प्रतिक्रिया",
    score: "अंक / स्कोर",
    gradeAssignment: "मूल्यांकन करें",
    aiTutor: "एआई ट्यूटर",
    studyGuides: "अध्ययन मार्गदर्शिकाएँ और सारांश",
    shortSummary: "संक्षिप्त सारांश",
    revisionNotes: "संशोधन नोट्स",
    examNotes: "परीक्षा नोट्स",
    oneMinuteReview: "1-मिनट समीक्षा",
    askAiTutor: "एआई ट्यूटर से पूछें"
  },
  French: {
    dashboard: "Tableau de bord",
    explore: "Explorer",
    generateLesson: "Générer leçon",
    myLibrary: "Ma bibliothèque",
    profile: "Profil",
    logout: "Déconnexion",
    welcomeBack: "Bon retour",
    totalLessons: "Total leçons",
    teacherAccount: "Compte Enseignant",
    studentAccount: "Compte Étudiant",
    last7Days: "7 derniers jours",
    recentLessons: "Leçons récentes",
    availableMaterials: "Supports d'étude disponibles",
    createFirstLesson: "Créez votre première leçon",
    noLessonsYet: "Aucune leçon pour l'instant.",
    noLessonsPublished: "Aucune leçon publiée par les enseignants pour le moment.",
    saveProfile: "Enregistrer le profil",
    teacherDetails: "Détails de l'enseignant",
    school: "École",
    subjectSpecialty: "Spécialité",
    webhookUrl: "URL Webhook",
    saveWebhook: "Enregistrer Webhook",
    geminiApiIntegration: "Intégration Gemini AI",
    geminiApiKey: "Clé API Gemini",
    saveApiKey: "Enregistrer la clé",
    lessonKit: "Kit de leçon",
    lessonPlan: "Plan de leçon",
    worksheet: "Feuille d'exercices",
    quiz: "Quiz d'entraînement",
    answerKey: "Corrigé",
    regenerate: "Régénérer",
    save: "Enregistrer",
    publish: "Publier",
    published: "Publié",
    email: "E-mail",
    backToLibrary: "Retour bibliothèque",
    backHome: "Retour accueil",
    studyMaterialLibrary: "Bibliothèque d'études",
    searchPlaceholder: "Rechercher par titre, matière...",
    lessonDetails: "Détails de la leçon",
    subject: "Matière",
    grade: "Niveau",
    topic: "Sujet",
    duration: "Durée",
    language: "Langue",
    learningObjectives: "Objectifs d'apprentissage",
    generate: "Générer la leçon",
    generating: "Génération...",
    assistantTitle: "Assistant d'étude IA",
    assistantWelcome: "Bonjour! Je suis votre assistant d'étude TechFlow AI. Posez-moi des questions sur l'apprentissage, l'enseignement, les révisions, la planification de cours ou le contenu éducatif.",
    chatPlaceholder: "Poser une question...",
    quickSummary: "Résumer les points clés",
    quickQuiz: "Posez-moi une question",
    quickSimplify: "Expliquer simplement",
    send: "Envoyer",
    newLesson: "Nouvelle leçon",
    welcomeText: "Votre assistant pédagogique IA.",
    welcomeStudentText: "Explorez les leçons publiées par les enseignants.",
    studyMaterial: "Matériel d'étude",
    apiPlaceholder: "AIzaSy...",
    emailCopied: "Leçon copiée dans le presse-papiers",
    connectedWebhook: "Connecté: Webhook Make.com",
    connectedGemini: "Connecté: Gemini AI (Direct)",
    builtInDemo: "Utilisation du générateur de démonstration intégré. Ajoutez une clé API Gemini ou un Webhook dans votre profil pour une vraie IA.",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    flashcards: "Cartes mémoire",
    quizGenerator: "Générateur de quiz",
    flip: "Retourner",
    next: "Suivant",
    previous: "Précédent",
    shuffle: "Mélanger",
    download: "Télécharger",
    difficulty: "Difficulté",
    easy: "Facile",
    medium: "Moyen",
    hard: "Difficile",
    readAloud: "Lecture vocale",
    pause: "Pause",
    resume: "Reprendre",
    stop: "Arrêter",
    regenerateFlashcards: "Régénérer les cartes",
    cardIndex: "Carte {current} sur {total}",
    downloadPdf: "Télécharger PDF",
    downloadFullKit: "Télécharger Kit Complet PDF",
    rubric: "Rubrique d'Évaluation",
    homework: "Devoirs",
    generateRubric: "Générer la Rubrique",
    generateHomework: "Générer les Devoirs",
    versions: "Historique des Versions",
    duplicate: "Dupliquer la Leçon",
    restore: "Restaurer",
    restored: "Version restaurée avec succès",
    viewPreviousVersions: "Historique des Versions",
    selectVersion: "Sélectionnez une version à restaurer",
    duplicationDialogTitle: "Dupliquer et Personnaliser la Leçon",
    assessmentType: "Type d'Évaluation",
    estimatedTime: "Temps Estimé",
    difficultyLevel: "Niveau de Difficulté",
    revertToThis: "Restaurer cette version",
    lessonsCreated: "Leçons Créées",
    lessonsPublished: "Leçons Publiées",
    lessonsShared: "Leçons Partagées",
    studentViews: "Vues des Étudiants",
    subjectDistribution: "Distribution par Matière",
    gradeDistribution: "Distribution par Niveau",
    usageTrends: "Tendances d'Utilisation",
    noVersions: "Aucune ancienne version trouvée pour cette leçon.",
    analytics: "Analyses",
    myProgress: "Ma Progression",
    classProgress: "Progression de la Classe",
    assignments: "Devoirs",
    createAssignment: "Créer un devoir",
    assignmentUrl: "Lien du devoir",
    dueDate: "Date limite",
    submitAssignment: "Soumettre le devoir",
    submissions: "Soumissions",
    streak: "Série",
    points: "Points",
    achievements: "Succès",
    leaderboard: "Classement",
    aiRecommendations: "Recommandations IA",
    generateRecommendations: "Générer les recommandations",
    studyPlan: "Plan d'étude",
    generateStudyPlan: "Générer le plan d'étude",
    feedback: "Commentaires",
    score: "Note",
    gradeAssignment: "Noter le devoir",
    aiTutor: "Tuteur IA",
    studyGuides: "Guides d'étude et Résumés",
    shortSummary: "Résumé court",
    revisionNotes: "Notes de révision",
    examNotes: "Notes d'examen",
    oneMinuteReview: "Révision d'une minute",
    askAiTutor: "Demander au tuteur IA"
  },
  Spanish: {
    dashboard: "Panel de control",
    explore: "Explorar",
    generateLesson: "Generar lección",
    myLibrary: "Mi biblioteca",
    profile: "Perfil",
    logout: "Cerrar sesión",
    welcomeBack: "Bienvenido de nuevo",
    totalLessons: "Total de lecciones",
    teacherAccount: "Cuenta de Profesor",
    studentAccount: "Cuenta de Estudiante",
    last7Days: "Últimos 7 días",
    recentLessons: "Lecciones recientes",
    availableMaterials: "Materiales de estudio disponibles",
    createFirstLesson: "Crea tu primera lección",
    noLessonsYet: "No hay lecciones aún.",
    noLessonsPublished: "Aún no hay lecciones publicadas por profesores.",
    saveProfile: "Guardar perfil",
    teacherDetails: "Detalles del profesor",
    school: "Escuela",
    subjectSpecialty: "Especialidad de la materia",
    webhookUrl: "URL del Webhook",
    saveWebhook: "Guardar webhook",
    geminiApiIntegration: "Integración de Gemini AI",
    geminiApiKey: "Clave API de Gemini",
    saveApiKey: "Guardar clave API",
    lessonKit: "Kit de lección",
    lessonPlan: "Plan de lección",
    worksheet: "Hoja de trabajo",
    quiz: "Quiz de práctica",
    answerKey: "Clave de respuestas",
    regenerate: "Regenerar",
    save: "Guardar",
    publish: "Publicar",
    published: "Publicado",
    email: "Correo electrónico",
    backToLibrary: "Volver a la biblioteca",
    backHome: "Volver al inicio",
    studyMaterialLibrary: "Biblioteca de material de estudio",
    searchPlaceholder: "Buscar por título, materia o tema...",
    lessonDetails: "Detalles de la lección",
    subject: "Materia",
    grade: "Grado",
    topic: "Tema",
    duration: "Duración",
    language: "Idioma",
    learningObjectives: "Objetivos de aprendizaje",
    generate: "Generar lección",
    generating: "Generando...",
    assistantTitle: "Asistente de estudio IA",
    assistantWelcome: "¡Hola! Soy tu asistente de estudio de TechFlow AI. Pregúntame cualquier cosa relacionada con el aprendizaje, la enseñanza, la revisión, la planificación de lecciones o el contenido educativo.",
    chatPlaceholder: "Hacer una pregunta...",
    quickSummary: "Resumir puntos clave",
    quickQuiz: "Hazme una pregunta",
    quickSimplify: "Explicar de forma sencilla",
    send: "Enviar",
    newLesson: "Nueva lección",
    welcomeText: "Tu asistente de enseñanza de IA.",
    welcomeStudentText: "Explora lecciones publicadas por profesores.",
    studyMaterial: "Material de estudio",
    apiPlaceholder: "AIzaSy...",
    emailCopied: "Lección copiada al portapapeles",
    connectedWebhook: "Conectado: Webhook de Make.com",
    connectedGemini: "Conectado: Gemini AI (Directo)",
    builtInDemo: "Usando el generador de demostración integrado. Agrega una clave API de Gemini o un Webhook en tu perfil para usar la IA real.",
    lightMode: "Modo claro",
    darkMode: "Modo oscuro",
    flashcards: "Tarjetas",
    quizGenerator: "Generador de quiz",
    flip: "Voltear",
    next: "Siguiente",
    previous: "Anterior",
    shuffle: "Barajar",
    download: "Descargar",
    difficulty: "Dificultad",
    easy: "Fácil",
    medium: "Medio",
    hard: "Difícil",
    readAloud: "Leer en voz alta",
    pause: "Pausar",
    resume: "Reanudar",
    stop: "Detener",
    regenerateFlashcards: "Regenerar tarjetas",
    cardIndex: "Tarjeta {current} de {total}",
    downloadPdf: "Descargar PDF",
    downloadFullKit: "Descargar Kit Completo PDF",
    rubric: "Rúbrica de Evaluación",
    homework: "Tarea",
    generateRubric: "Generar Rúbrica",
    generateHomework: "Generar Tarea",
    versions: "Historial de Versiones",
    duplicate: "Duplicar Lección",
    restore: "Restaurar",
    restored: "Versión restaurada con éxito",
    viewPreviousVersions: "Historial de Versiones",
    selectVersion: "Seleccione una versión para restaurar",
    duplicationDialogTitle: "Duplicar y Personalizar Lección",
    assessmentType: "Tipo de Evaluación",
    estimatedTime: "Tiempo Estimado",
    difficultyLevel: "Nivel de Dificultad",
    revertToThis: "Restaurar esta versión",
    lessonsCreated: "Lecciones Creadas",
    lessonsPublished: "Lecciones Publicadas",
    lessonsShared: "Lecciones Compartidas",
    studentViews: "Vistas de Estudiantes",
    subjectDistribution: "Distribución por Materia",
    gradeDistribution: "Distribución por Grado",
    usageTrends: "Tendencias de Uso",
    noVersions: "No se encontraron versiones anteriores de esta lección.",
    analytics: "Estadísticas",
    myProgress: "Mi Progreso",
    classProgress: "Progreso de la Clase",
    assignments: "Tareas",
    createAssignment: "Crear Tarea",
    assignmentUrl: "Enlace de la tarea",
    dueDate: "Fecha límite",
    submitAssignment: "Entregar Tarea",
    submissions: "Entregas",
    streak: "Racha",
    points: "Puntos",
    achievements: "Logros",
    leaderboard: "Tabla de clasificación",
    aiRecommendations: "Recomendaciones de IA",
    generateRecommendations: "Generar Recomendaciones",
    studyPlan: "Plan de estudio",
    generateStudyPlan: "Generar Plan de Estudio",
    feedback: "Comentarios",
    score: "Calificación",
    gradeAssignment: "Calificar Tarea",
    aiTutor: "Tutor de IA",
    studyGuides: "Guías de estudio y resúmenes",
    shortSummary: "Resumen corto",
    revisionNotes: "Notas de revisión",
    examNotes: "Notas del examen",
    oneMinuteReview: "Revisión de un minuto",
    askAiTutor: "Preguntar al tutor de IA"
  },
  German: {
    dashboard: "Dashboard",
    explore: "Erkunden",
    generateLesson: "Lektion erstellen",
    myLibrary: "Meine Bibliothek",
    profile: "Profil",
    logout: "Abmelden",
    welcomeBack: "Willkommen zurück",
    totalLessons: "Lektionen insgesamt",
    teacherAccount: "Lehrerkonto",
    studentAccount: "Schülerkonto",
    last7Days: "Letzte 7 Tage",
    recentLessons: "Aktuelle Lektionen",
    availableMaterials: "Verfügbares Lernmaterial",
    createFirstLesson: "Erstelle deine erste Lektion",
    noLessonsYet: "Noch keine Lektionen vorhanden.",
    noLessonsPublished: "Bisher wurden noch keine Lektionen von Lehrern veröffentlicht.",
    saveProfile: "Profil speichern",
    teacherDetails: "Lehrerdetails",
    school: "Schule",
    subjectSpecialty: "Fachgebiet",
    webhookUrl: "Webhook-URL",
    saveWebhook: "Webhook speichern",
    geminiApiIntegration: "Gemini AI Integration",
    geminiApiKey: "Gemini API-Schlüssel",
    saveApiKey: "Schlüssel speichern",
    lessonKit: "Lektions-Kit",
    lessonPlan: "Verlaufsplan",
    worksheet: "Arbeitsblatt",
    quiz: "Übungsquiz",
    answerKey: "Lösungsschlüssel",
    regenerate: "Regenerieren",
    save: "Speichern",
    publish: "Veröffentlichen",
    published: "Veröffentlicht",
    email: "E-Mail",
    backToLibrary: "Zurück zur Bibliothek",
    backHome: "Zurück zur Startseite",
    studyMaterialLibrary: "Lernmaterialbibliothek",
    searchPlaceholder: "Suche nach Titel, Fach oder Thema...",
    lessonDetails: "Lektionsdetails",
    subject: "Fach",
    grade: "Klasse",
    topic: "Thema",
    duration: "Dauer",
    language: "Sprache",
    learningObjectives: "Lernziele",
    generate: "Lektion generieren",
    generating: "Generiere...",
    assistantTitle: "KI-Lernassistent",
    assistantWelcome: "Hallo! Ich bin dein TechFlow AI Lernassistent. Frage mich alles über das Lernen, Lehren, Wiederholen, Unterrichtsplanung oder Bildungsinhalte.",
    chatPlaceholder: "Frage stellen...",
    quickSummary: "Punkte zusammenfassen",
    quickQuiz: "Stelle mir eine Frage",
    quickSimplify: "Einfach erklären",
    send: "Senden",
    newLesson: "Neue Lektion",
    welcomeText: "Ihr KI-Lehrassistent.",
    welcomeStudentText: "Entdecken Sie von Lehrern veröffentlichte Lektionen.",
    studyMaterial: "Lernmaterial",
    apiPlaceholder: "AIzaSy...",
    emailCopied: "Lektion in die Zwischenablage kopiert",
    connectedWebhook: "Verbunden: Make.com Webhook",
    connectedGemini: "Verbunden: Gemini AI (Direkt)",
    builtInDemo: "Verwendung des integrierten Demo-Generators. Fügen Sie einen Gemini API-Schlüssel oder Webhook in Ihrem Profil hinzu, um echte KI zu nutzen.",
    lightMode: "Heller Modus",
    darkMode: "Dunkler Modus",
    flashcards: "Karteikarten",
    quizGenerator: "Quiz-Generator",
    flip: "Umdrehen",
    next: "Weiter",
    previous: "Zurück",
    shuffle: "Mischen",
    download: "Herunterladen",
    difficulty: "Schwierigkeit",
    easy: "Leicht",
    medium: "Mittel",
    hard: "Schwer",
    readAloud: "Vorlesen",
    pause: "Pause",
    resume: "Fortsetzen",
    stop: "Stopp",
    regenerateFlashcards: "Karten neu generieren",
    cardIndex: "Karte {current} von {total}",
    downloadPdf: "PDF herunterladen",
    downloadFullKit: "Komplettes Kit als PDF herunterladen",
    rubric: "Bewertungsrubrik",
    homework: "Hausaufgabe",
    generateRubric: "Rubrik erstellen",
    generateHomework: "Hausaufgabe erstellen",
    versions: "Versionsverlauf",
    duplicate: "Lektion duplizieren",
    restore: "Wiederherstellen",
    restored: "Version erfolgreich wiederhergestellt",
    viewPreviousVersions: "Versionsverlauf",
    selectVersion: "Version zum Wiederherstellen auswählen",
    duplicationDialogTitle: "Lektion duplizieren und anpassen",
    assessmentType: "Bewertungsart",
    estimatedTime: "Geschätzte Zeit",
    difficultyLevel: "Schwierigkeitsgrad",
    revertToThis: "Diese Version wiederherstellen",
    lessonsCreated: "Erstellte Lektionen",
    lessonsPublished: "Veröffentlichte Lektionen",
    lessonsShared: "Geteilte Lektionen",
    studentViews: "Schüleraufrufe",
    subjectDistribution: "Fachverteilung",
    gradeDistribution: "Klassenverteilung",
    usageTrends: "Nutzungstrends",
    noVersions: "Keine älteren Versionen für diese Lektion gefunden.",
    analytics: "Analysen",
    myProgress: "Mein Fortschritt",
    classProgress: "Klassenfortschritt",
    assignments: "Aufgaben",
    createAssignment: "Aufgabe erstellen",
    assignmentUrl: "Aufgaben-Link",
    dueDate: "Fälligkeitsdatum",
    submitAssignment: "Aufgabe abgeben",
    submissions: "Abgaben",
    streak: "Serie",
    points: "Punkte",
    achievements: "Erfolge",
    leaderboard: "Bestenliste",
    aiRecommendations: "KI-Empfehlungen",
    generateRecommendations: "Empfehlungen generieren",
    studyPlan: "Lernplan",
    generateStudyPlan: "Lernplan generieren",
    feedback: "Feedback",
    score: "Bewertung",
    gradeAssignment: "Aufgabe bewerten",
    aiTutor: "KI-Tutor",
    studyGuides: "Studienführer & Zusammenfassungen",
    shortSummary: "Kurze Zusammenfassung",
    revisionNotes: "Wiederholungsnotizen",
    examNotes: "Prüfungsnotizen",
    oneMinuteReview: "Ein-Minuten-Rückblick",
    askAiTutor: "KI-Tutor fragen"
  },
  Japanese: {
    dashboard: "ダッシュボード",
    explore: "探す",
    generateLesson: "レッスン作成",
    myLibrary: "マイライブラリ",
    profile: "プロフィール",
    logout: "ログアウト",
    welcomeBack: "おかえりなさい",
    totalLessons: "レッスン合計",
    teacherAccount: "教師アカウント",
    studentAccount: "生徒アカウント",
    last7Days: "過去7日間",
    recentLessons: "最近のレッスン",
    availableMaterials: "利用可能な学習教材",
    createFirstLesson: "最初のレッスンを作成する",
    noLessonsYet: "レッスンはまだありません。",
    noLessonsPublished: "教師によって公開されたレッスンはまだありません。",
    saveProfile: "プロフィール保存",
    teacherDetails: "教師の詳細情報",
    school: "学校",
    subjectSpecialty: "専門科目",
    webhookUrl: "Webhook URL",
    saveWebhook: "Webhook保存",
    geminiApiIntegration: "Gemini AI 連携",
    geminiApiKey: "Gemini API キー",
    saveApiKey: "APIキー保存",
    lessonKit: "レッスンキット",
    lessonPlan: "指導案",
    worksheet: "ワークシート",
    quiz: "練習クイズ",
    answerKey: "解答集",
    regenerate: "再生成",
    save: "保存",
    publish: "公開する",
    published: "公開中",
    email: "メール送信",
    backToLibrary: "ライブラリに戻る",
    backHome: "ホームに戻る",
    studyMaterialLibrary: "教材ライブラリ",
    searchPlaceholder: "タイトル、教科、トピックで検索...",
    lessonDetails: "レッスンの詳細",
    subject: "教科",
    grade: "学年",
    topic: "トピック",
    duration: "時間",
    language: "言語",
    learningObjectives: "学習目標",
    generate: "レッスン生成",
    generating: "生成中...",
    assistantTitle: "AI学習アシスタント",
    assistantWelcome: "こんにちは！TechFlow AI学習アシスタントです。学習、指導、復習、指導案作成、教育コンテンツに関することなら何でも聞いてください。",
    chatPlaceholder: "質問を入力...",
    quickSummary: "重要ポイントを要約",
    quickQuiz: "クイズを出して",
    quickSimplify: "簡単に説明して",
    send: "送信",
    newLesson: "新規レッスン",
    welcomeText: "あなたのAI指導アシスタント。",
    welcomeStudentText: "先生方が公開したレッスン教材を学びましょう。",
    studyMaterial: "学習教材",
    apiPlaceholder: "AIzaSy...",
    emailCopied: "レッスンをクリップボードにコピーしました",
    connectedWebhook: "接続完了: Make.com Webhook",
    connectedGemini: "接続完了: Gemini AI (直接)",
    builtInDemo: "内蔵のデモ用生成エンジンを使用しています。本物のAIを利用するには、プロフィール画面でGemini APIキーまたはWebhookを設定してください。",
    lightMode: "ライトモード",
    darkMode: "ダークモード",
    flashcards: "単語カード",
    quizGenerator: "クイズ作成器",
    flip: "めくる",
    next: "次へ",
    previous: "前へ",
    shuffle: "シャッフル",
    download: "ダウンロード",
    difficulty: "難易度",
    easy: "簡単",
    medium: "普通",
    hard: "難しい",
    readAloud: "音声読み上げ",
    pause: "一時停止",
    resume: "再開",
    stop: "停止",
    regenerateFlashcards: "カード再生成",
    cardIndex: "{total} 枚中 {current} 枚目",
    downloadPdf: "PDFをダウンロード",
    downloadFullKit: "フルキットPDFをダウンロード",
    rubric: "評価ルーブリック",
    homework: "宿題",
    generateRubric: "ルーブリック生成",
    generateHomework: "宿題生成",
    versions: "バージョン履歴",
    duplicate: "レッスンを複製",
    restore: "復元",
    restored: "バージョンが正常に復元されました",
    viewPreviousVersions: "バージョン履歴",
    selectVersion: "復元するバージョンを選択",
    duplicationDialogTitle: "レッスンを複製してカスタマイズ",
    assessmentType: "評価タイプ",
    estimatedTime: "所要時間",
    difficultyLevel: "難易度レベル",
    revertToThis: "このバージョンを復元",
    lessonsCreated: "作成されたレッスン",
    lessonsPublished: "公開されたレッスン",
    lessonsShared: "共有されたレッスン",
    studentViews: "生徒の閲覧数",
    subjectDistribution: "科目分布",
    gradeDistribution: "学年分布",
    usageTrends: "利用傾向",
    noVersions: "このレッスンの古いバージョンは見つかりませんでした。",
    analytics: "分析",
    myProgress: "マイ進捗",
    classProgress: "クラスの進捗",
    assignments: "課題",
    createAssignment: "課題を作成",
    assignmentUrl: "課題リンク",
    dueDate: "提出期限",
    submitAssignment: "課題を提出",
    submissions: "提出物",
    streak: "継続日数",
    points: "ポイント",
    achievements: "実績",
    leaderboard: "リーダーボード",
    aiRecommendations: "AIおすすめ",
    generateRecommendations: "おすすめを生成",
    studyPlan: "学習計画",
    generateStudyPlan: "学習計画を生成",
    feedback: "フィードバック",
    score: "スコア",
    gradeAssignment: "課題を評価",
    aiTutor: "AIチューター",
    studyGuides: "学習ガイドと要約",
    shortSummary: "短い要約",
    revisionNotes: "復習ノート",
    examNotes: "試験対策ノート",
    oneMinuteReview: "1分間レビュー",
    askAiTutor: "AIチューターに質問する"
  },
  Chinese: {
    dashboard: "仪表盘",
    explore: "浏览库",
    generateLesson: "生成教案",
    myLibrary: "我的库",
    profile: "个人资料",
    logout: "登出",
    welcomeBack: "欢迎回来",
    totalLessons: "教案总数",
    teacherAccount: "教师账户",
    studentAccount: "学生账户",
    last7Days: "过去 7 天",
    recentLessons: "最近教案",
    availableMaterials: "可用学习材料",
    createFirstLesson: "创建您的第一个教案",
    noLessonsYet: "暂无教案。",
    noLessonsPublished: "教师尚未发布任何教案。",
    saveProfile: "保存资料",
    teacherDetails: "教师详情",
    school: "学校",
    subjectSpecialty: "专业科目",
    webhookUrl: "Webhook 链接",
    saveWebhook: "保存 Webhook",
    geminiApiIntegration: "Gemini AI 集成",
    geminiApiKey: "Gemini API 密钥",
    saveApiKey: "保存 API 密钥",
    lessonKit: "教案配套包",
    lessonPlan: "课时计划",
    worksheet: "随堂练习卷",
    quiz: "测验小题",
    answerKey: "参考答案",
    regenerate: "重新生成",
    save: "保存",
    publish: "发布",
    published: "已发布",
    email: "发送邮件",
    backToLibrary: "返回库",
    backHome: "返回首页",
    studyMaterialLibrary: "学习资源库",
    searchPlaceholder: "按标题、科目、主题搜索...",
    lessonDetails: "教案详情",
    subject: "科目",
    grade: "年级",
    topic: "主题",
    duration: "时长",
    language: "语言",
    learningObjectives: "教学目标",
    generate: "生成教案",
    generating: "生成中...",
    assistantTitle: "AI 学习助手",
    assistantWelcome: "您好！我是您的 TechFlow AI 学习助手。有关学习、教学、复习、教学计划或任何教育内容，都可以向我提问。",
    chatPlaceholder: "输入您的问题...",
    quickSummary: "归纳核心要点",
    quickQuiz: "考考我",
    quickSimplify: "通俗易懂地解释",
    send: "发送",
    newLesson: "新建教案",
    welcomeText: "您的 AI 助教。",
    welcomeStudentText: "浏览教师发布的学习资源。",
    studyMaterial: "学习资源",
    apiPlaceholder: "AIzaSy...",
    emailCopied: "教案内容已成功复制到剪贴板",
    connectedWebhook: "已连接: Make.com Webhook",
    connectedGemini: "已连接: Gemini AI (直连)",
    builtInDemo: "当前正在使用内置演示生成器。如需真实的AI生成效果，请在“个人资料”页面配置 Gemini API 密钥或 Webhook 链接。",
    lightMode: "浅色模式",
    darkMode: "深色模式",
    flashcards: "记忆卡",
    quizGenerator: "测验生成器",
    flip: "翻转",
    next: "下一张",
    previous: "上一张",
    shuffle: "打乱",
    download: "下载",
    difficulty: "难度",
    easy: "简单",
    medium: "中等",
    hard: "困难",
    readAloud: "朗读",
    pause: "暂停",
    resume: "恢复",
    stop: "停止",
    regenerateFlashcards: "重新生成卡片",
    cardIndex: "第 {current} 张，共 {total} 张",
    downloadPdf: "下载 PDF",
    downloadFullKit: "下载完整配套包 PDF",
    rubric: "评分量规 (Rubric)",
    homework: "课后作业",
    generateRubric: "生成评分量规",
    generateHomework: "生成课后作业",
    versions: "版本历史",
    duplicate: "复制教案",
    restore: "还原",
    restored: "版本还原成功",
    viewPreviousVersions: "版本历史",
    selectVersion: "选择要还原的版本",
    duplicationDialogTitle: "复制并自定义教案",
    assessmentType: "评估类型",
    estimatedTime: "预计完成时间",
    difficultyLevel: "难度级别",
    revertToThis: "还原此版本",
    lessonsCreated: "已创建教案",
    lessonsPublished: "已发布教案",
    lessonsShared: "已分享教案",
    studentViews: "学生浏览量",
    subjectDistribution: "科目分布",
    gradeDistribution: "年级分布",
    usageTrends: "使用趋势",
    noVersions: "未找到此教案的历史版本。",
    analytics: "统计分析",
    myProgress: "我的进度",
    classProgress: "班级进度",
    assignments: "作业",
    createAssignment: "创建作业",
    assignmentUrl: "作业链接",
    dueDate: "截止日期",
    submitAssignment: "提交作业",
    submissions: "已提交作业",
    streak: "连续学习",
    points: "积分",
    achievements: "成就",
    leaderboard: "排行榜",
    aiRecommendations: "AI 推荐",
    generateRecommendations: "生成推荐",
    studyPlan: "学习计划",
    generateStudyPlan: "生成学习计划",
    feedback: "反馈",
    score: "得分",
    gradeAssignment: "批改作业",
    aiTutor: "AI 导师",
    studyGuides: "学习指南与摘要",
    shortSummary: "简短摘要",
    revisionNotes: "复习笔记",
    examNotes: "考试笔记",
    oneMinuteReview: "一分钟回顾",
    askAiTutor: "向 AI 导师提问"
  },
};

type LanguageContextProps = {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextProps>({
  language: "English",
  setLanguage: async () => {},
  t: (k) => k
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>("English");

  // Load language preference initially
  useEffect(() => {
    // 1. Check local storage
    const stored = localStorage.getItem("preferred_language") as Language | null;
    if (stored && SUPPORTED_LANGUAGES.some((l) => l.name === stored)) {
      setLanguageState(stored);
    }

    // 2. If logged in, fetch from DB
    if (!user) return;
    (async () => {
      try {
        const { data, error } = await supabase
          .from("profiles")
          .select("preferred_language")
          .eq("id", user.id)
          .maybeSingle();

        if (data?.preferred_language && SUPPORTED_LANGUAGES.some((l) => l.name === data.preferred_language)) {
          const dbLang = data.preferred_language as Language;
          setLanguageState(dbLang);
          localStorage.setItem("preferred_language", dbLang);
        }
      } catch (err) {
        console.error("Error loading language from profiles database:", err);
      }
    })();
  }, [user]);

  const setLanguage = async (newLang: Language) => {
    setLanguageState(newLang);
    localStorage.setItem("preferred_language", newLang);

    if (user) {
      try {
        const { error } = await supabase
          .from("profiles")
          .update({ preferred_language: newLang })
          .eq("id", user.id);

        if (error) {
          console.warn("Failed to sync language to database profiles:", error.message);
        }
      } catch (err) {
        console.error("Error syncing language to database profiles:", err);
      }
    }
  };

  const t = (key: string): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.English;
    return dict[key] || TRANSLATIONS.English[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
