/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIdRouteImport } from './routes/study.$id'
import { Route as AssignmentIdRouteImport } from './routes/assignment.$id'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppGenerateRouteImport } from './routes/_app/generate'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClassProgressRouteImport } from './routes/_app/class-progress'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppLessonsIdRouteImport } from './routes/_app/lessons.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIdRoute = StudyIdRouteImport.update({
  id: '/study/$id',
  path: '/study/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentIdRoute = AssignmentIdRouteImport.update({
  id: '/assignment/$id',
  path: '/assignment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateRoute = AppGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassProgressRoute = AppClassProgressRouteImport.update({
  id: '/class-progress',
  path: '/class-progress',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsIdRoute = AppLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/class-progress': typeof AppClassProgressRoute
  '/dashboard': typeof AppDashboardRoute
  '/generate': typeof AppGenerateRoute
  '/library': typeof AppLibraryRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/tutor': typeof AppTutorRoute
  '/assignment/$id': typeof AssignmentIdRoute
  '/study/$id': typeof StudyIdRoute
  '/lessons/$id': typeof AppLessonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/class-progress': typeof AppClassProgressRoute
  '/dashboard': typeof AppDashboardRoute
  '/generate': typeof AppGenerateRoute
  '/library': typeof AppLibraryRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/tutor': typeof AppTutorRoute
  '/assignment/$id': typeof AssignmentIdRoute
  '/study/$id': typeof StudyIdRoute
  '/lessons/$id': typeof AppLessonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/class-progress': typeof AppClassProgressRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/generate': typeof AppGenerateRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/tutor': typeof AppTutorRoute
  '/assignment/$id': typeof AssignmentIdRoute
  '/study/$id': typeof StudyIdRoute
  '/_app/lessons/$id': typeof AppLessonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/analytics'
    | '/class-progress'
    | '/dashboard'
    | '/generate'
    | '/library'
    | '/profile'
    | '/progress'
    | '/tutor'
    | '/assignment/$id'
    | '/study/$id'
    | '/lessons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/analytics'
    | '/class-progress'
    | '/dashboard'
    | '/generate'
    | '/library'
    | '/profile'
    | '/progress'
    | '/tutor'
    | '/assignment/$id'
    | '/study/$id'
    | '/lessons/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/explore'
    | '/login'
    | '/_app/analytics'
    | '/_app/class-progress'
    | '/_app/dashboard'
    | '/_app/generate'
    | '/_app/library'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/tutor'
    | '/assignment/$id'
    | '/study/$id'
    | '/_app/lessons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  AssignmentIdRoute: typeof AssignmentIdRoute
  StudyIdRoute: typeof StudyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$id': {
      id: '/study/$id'
      path: '/study/$id'
      fullPath: '/study/$id'
      preLoaderRoute: typeof StudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment/$id': {
      id: '/assignment/$id'
      path: '/assignment/$id'
      fullPath: '/assignment/$id'
      preLoaderRoute: typeof AssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generate': {
      id: '/_app/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AppGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/class-progress': {
      id: '/_app/class-progress'
      path: '/class-progress'
      fullPath: '/class-progress'
      preLoaderRoute: typeof AppClassProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/$id': {
      id: '/_app/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof AppLessonsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppClassProgressRoute: typeof AppClassProgressRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGenerateRoute: typeof AppGenerateRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppTutorRoute: typeof AppTutorRoute
  AppLessonsIdRoute: typeof AppLessonsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppClassProgressRoute: AppClassProgressRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGenerateRoute: AppGenerateRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppTutorRoute: AppTutorRoute,
  AppLessonsIdRoute: AppLessonsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  AssignmentIdRoute: AssignmentIdRoute,
  StudyIdRoute: StudyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
